# Generated by Django 4.0.8 on 2025-03-31 10:28

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='scheduled_time',
        ),
        migrations.RemoveField(
            model_name='service',
            name='category',
        ),
        migrations.RemoveField(
            model_name='service',
            name='description',
        ),
        migrations.RemoveField(
            model_name='service',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_service_provider',
        ),
        migrations.RemoveField(
            model_name='user',
            name='rating',
        ),
        migrations.AddField(
            model_name='order',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='结束时间'),
        ),
        migrations.AddField(
            model_name='order',
            name='start_time',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='开始时间'),
        ),
        migrations.AddField(
            model_name='service',
            name='service_type',
            field=models.CharField(choices=[('保洁', '保洁'), ('维修', '维修')], default='保洁', max_length=10, verbose_name='服务类型'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('C', '普通用户'), ('B', '服务提供者'), ('ADMIN', '管理员')], default='C', max_length=10, verbose_name='用户角色'),
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('正常', '正常'), ('冻结', '冻结'), ('注销', '注销')], default='正常', max_length=10, verbose_name='账户状态'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='order',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.service', verbose_name='服务项目'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('待支付', '待支付'), ('已支付', '已支付'), ('已取消', '已取消'), ('已完成', '已完成')], default='待支付', max_length=10, verbose_name='订单状态'),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=50, verbose_name='服务名称'),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(500)], verbose_name='价格'),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='icon',
            field=models.CharField(max_length=50, verbose_name='图标代码'),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='name',
            field=models.CharField(max_length=50, verbose_name='类别名称'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='请输入正确的手机号码', regex='^1[3-9]\\d{9}$')], verbose_name='手机号'),
        ),
        migrations.AlterField(
            model_name='verificationcode',
            name='code',
            field=models.CharField(max_length=6, verbose_name='验证码'),
        ),
        migrations.AlterField(
            model_name='verificationcode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='verificationcode',
            name='phone',
            field=models.CharField(max_length=11, verbose_name='手机号'),
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='昵称只能包含中文、字母和数字，长度2-10位', regex='^[\\w\\u4e00-\\u9fa5]{2,10}$')], verbose_name='昵称')),
                ('gender', models.CharField(choices=[('男', '男'), ('女', '女'), ('未知', '未知')], default='未知', max_length=10, verbose_name='性别')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='出生日期')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png']), django.core.validators.MaxValueValidator(2097152)], verbose_name='头像')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户账号')),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
                'db_table': 'user_info',
            },
        ),
        migrations.CreateModel(
            name='UserCertification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('real_name', models.CharField(max_length=50, verbose_name='真实姓名')),
                ('id_card', models.CharField(max_length=18, verbose_name='身份证号')),
                ('status', models.CharField(choices=[('待审核', '待审核'), ('通过', '通过'), ('驳回', '驳回')], default='待审核', max_length=10, verbose_name='认证状态')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '实名认证',
                'verbose_name_plural': '实名认证',
                'db_table': 'user_certification',
            },
        ),
        migrations.CreateModel(
            name='ServiceProviderInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_area', models.CharField(max_length=100, verbose_name='服务范围')),
                ('introduction', models.CharField(max_length=100, verbose_name='简介')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '服务者信息',
                'verbose_name_plural': '服务者信息',
                'db_table': 'service_provider_info',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='评价内容')),
                ('status', models.CharField(choices=[('待审核', '待审核'), ('通过', '通过'), ('驳回', '驳回')], default='待审核', max_length=10, verbose_name='审核状态')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.order', verbose_name='订单')),
            ],
            options={
                'verbose_name': '评价',
                'verbose_name_plural': '评价',
                'db_table': 'review',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='金额')),
                ('payment_method', models.CharField(choices=[('微信', '微信'), ('支付宝', '支付宝')], max_length=10, verbose_name='支付方式')),
                ('channel_fee', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='手续费')),
                ('status', models.CharField(choices=[('成功', '成功'), ('失败', '失败')], max_length=10, verbose_name='支付状态')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.order', verbose_name='订单')),
            ],
            options={
                'verbose_name': '支付记录',
                'verbose_name_plural': '支付记录',
                'db_table': 'payment',
            },
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_url', models.FileField(upload_to='certificates/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg'])], verbose_name='证书文件')),
                ('status', models.CharField(choices=[('待审核', '待审核'), ('通过', '通过'), ('驳回', '驳回')], default='待审核', max_length=10, verbose_name='审核状态')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.serviceproviderinfo', verbose_name='服务者')),
            ],
            options={
                'verbose_name': '资质证书',
                'verbose_name_plural': '资质证书',
                'db_table': 'certification',
            },
        ),
        migrations.CreateModel(
            name='AfterSales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('退款', '退款'), ('返工', '返工'), ('投诉', '投诉')], max_length=10, verbose_name='售后类型')),
                ('status', models.CharField(choices=[('待处理', '待处理'), ('已解决', '已解决'), ('驳回', '驳回')], default='待处理', max_length=10, verbose_name='工单状态')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.order', verbose_name='订单')),
            ],
            options={
                'verbose_name': '售后工单',
                'verbose_name_plural': '售后工单',
                'db_table': 'after_sales',
            },
        ),
        migrations.CreateModel(
            name='AddressBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, verbose_name='服务地址')),
                ('is_default', models.BooleanField(default=False, verbose_name='默认地址')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '地址簿',
                'verbose_name_plural': '地址簿',
                'db_table': 'address_book',
            },
        ),
        migrations.AddField(
            model_name='service',
            name='provider',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.serviceproviderinfo', verbose_name='服务者'),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.addressbook', verbose_name='服务地址'),
        ),
        migrations.AlterField(
            model_name='order',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.serviceproviderinfo', verbose_name='服务者'),
        ),
        migrations.AddConstraint(
            model_name='addressbook',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('user', 'is_default'), name='unique_default_address'),
        ),
    ]
